tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "ffmpeg"
brew "gh"
brew "git"
brew "imagemagick"
brew "jq"
brew "openssl@3"
brew "postgresql@14", restart_service: true
brew "rbenv"
brew "sqlite"
brew "wget"
brew "heroku/brew/heroku"
cask "visual-studio-code"
